import { DateRange } from '@mui/lab/DateRangePicker/RangeTypes'
import { AppBar, Container, Paper, Stack, Toolbar, Typography } from '@mui/material'
import { Box } from '@mui/system'
import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { AppDateRangePicker } from '../components/AppDateRangePicker'
import { Footer } from '../components/Footer'
import { HealthDataChart } from '../components/HealthDataChart'
import { data as d } from '../data'
import HealthData from '../models/HealthData'

const Home: NextPage = () => {
  const [data, setData] = React.useState<HealthData[]>(d)
  const [dateRange, setDateRange] = React.useState<DateRange<Date>>([new Date(Date.now() - 60 * 60 * 24 * 365 * 1000), new Date()])
  const onChangeDateRange = (range: DateRange<Date>) => {
    setDateRange(range)
    const [fromDate, toDate] = range
    if (fromDate && toDate) {
      const newData = d.filter(({ timestamp }) => fromDate <= timestamp && timestamp <= toDate)
      setData(newData)
    }
  }
  return (
    <Container maxWidth='md' disableGutters>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AppBar position='static'>
        <Toolbar>
          <Typography variant='h6' sx={{ flexGrow: 1 }}>
            weight.53ningen.com
          </Typography>
        </Toolbar>
      </AppBar>
      <Paper square>
        <Box p={2} pt={4}>
          <Stack spacing={4}>
            <Box mr='auto' ml='auto'>
              <AppDateRangePicker dateRange={dateRange} setDateRange={onChangeDateRange} />
            </Box>
            <Box width='100%' height='25rem'>
              <HealthDataChart data={data} />
            </Box>
            <Box>
              <p>REST API</p>
              <p>GraphQL API</p>
            </Box>
          </Stack>
        </Box>
      </Paper>
      <Footer />
    </Container>
  )
}

export default Home
